# Interface/Settings/about_settings.py
import customtkinter as ctk

def create_about_tab(globals, about_frame):
    """
    Creates the about tab and initializes widgets.

            Parameters:
                    globals: Global variables
                    about_frame: The main frame of the about tab
    """

    ctk.CTkLabel(about_frame, 
             text="About", 
             anchor="center").pack(fill="x", pady=20, padx=10)

    ctk.CTkLabel(about_frame,
                 justify="left",
                 text=f"Personal Everything Assistant Running Locally\n\n" \
                        f"Pearl is your assistant.\n\n" \
                        f"She is 100% private and runs locally on your computer.\n\n" \
                        f"Requirements:\n\n" \
                        f"- Ollama (with at least one LLM - llama3.2:latest is currently the most compatible).\n" \
                        f"- Kokoro Fast-API for TTS integration.\n\n" \
                        f"Currently Supported Operating Systems:\n\n" \
                        f"- Linux Mint\n" \
                        f"- Windows 11\n\n" \
                        f"Disclaimer - Third-Party AI Models\n\n" \
                        f"Pearl integrates third-party artificial intelligence models selected by the user. \n" \
                        f"The developer of this software is not responsible for the accuracy, appropriateness, \n" \
                        f"legality, or safety of any output generated by these AI models. All responses from \n" \
                        f"the AI are provided 'AS-IS' with no warrenties of any kind, express or implied. \n" \
                        f"Selecting an AI model, configurings its safeguards, and ensuring safe interaction are \n" \
                        f"entirely the user's responsibility. By using Pearl, you acknowledge that any \n" \
                        f"consequences arising from AI output are solely your own.\n\n" \
                        f"Have fun!").pack(padx=5, pady=5)

    ctk.CTkLabel(about_frame, 
             text=f"Current Version: {globals.current_version}", 
             anchor="center").pack(fill="x", pady=20, padx=10)

    ctk.CTkButton(about_frame, text="View Setup Page", command= lambda: bring_back_setup()).pack(padx=5, pady=5)

    def bring_back_setup():
        """Reinitiates the setup window."""
        globals.settings_overlay.pack_forget()
        globals.setup_page.pack(fill="both", expand=True, padx=10, pady=10)
