# Interface/Settings/about_settings.py
import customtkinter as ctk
import Utils.fonts as fonts
import webbrowser
from CTkToolTip import CTkToolTip

def create_about_tab(globals, about_frame):
    """
    Creates the about tab and initializes widgets.

            Parameters:
                    globals: Global variables
                    about_frame: The main frame of the about tab
    """

    ctk.CTkLabel(about_frame, 
             text="About", 
             font=fonts.title_font,
             anchor="center").pack(fill="x", pady=20, padx=10)

    ctk.CTkLabel(about_frame,
                 justify="left",
                 text=f"Personal Everything Assistant Running Locally\n\n" \
                        f"Pearl is your assistant.\n\n" \
                        f"She is 100% private and runs locally on your computer.\n\n" \
                        f"Requirements:\n\n" \
                        f"- Ollama (with at least one LLM - llama3.2:latest is currently the most compatible).\n" \
                        f"- Kokoro Fast-API for TTS integration.\n\n" \
                        f"Currently Supported on Linux and Windows.\n\n" \
                        f"Icon by Twoeliz\n\n" \
                        f"Disclaimer - Third-Party AI Models\n\n" \
                        f"Pearl integrates third-party artificial intelligence models selected by the user. \n" \
                        f"The developer of this software is not responsible for the accuracy, appropriateness, \n" \
                        f"legality, or safety of any output generated by these AI models. All responses from \n" \
                        f"the AI are provided 'AS-IS' with no warrenties of any kind, express or implied. \n" \
                        f"Selecting an AI model, configurings its safeguards, and ensuring safe interaction are \n" \
                        f"entirely the user's responsibility. By using Pearl, you acknowledge that any \n" \
                        f"consequences arising from AI output are solely your own.\n\n" \
                        f"Have fun!").pack(padx=5, pady=5)

    ctk.CTkLabel(about_frame, 
             text=f"Current Version: {globals.current_version}", 
             anchor="center").pack(fill="x", pady=20, padx=10)

    buttons_frame = ctk.CTkFrame(about_frame, fg_color="transparent")
    buttons_frame.pack(padx=10, pady=10)

    ctk.CTkButton(buttons_frame, text="View Setup Page", command= lambda: bring_back_setup()).grid(row=0, column=0, padx=5)
    ctk.CTkButton(buttons_frame, text="View Changelog", command= lambda: show_changelog()).grid(row=0, column=1, padx=5)

    github_button = ctk.CTkButton(buttons_frame, text="View Github", command= lambda: webbrowser.open(url="https://github.com/pdschneider/Pearl"))
    github_button.grid(row=0, column=2, padx=5)
    CTkToolTip(github_button, message="Opens in default web browser", delay=0.6, follow=True, padx=10, pady=5)

    def bring_back_setup():
        """Reinitiates the setup window."""
        globals.settings_overlay.pack_forget()
        globals.setup_page.pack(fill="both", expand=True, padx=10, pady=0)

    def show_changelog():
        """Brings up the changelog window."""
        globals.settings_overlay.pack_forget()
        globals.chat_page.pack_forget()
        globals.changelog.pack(fill="both", expand=True, padx=10, pady=0)